### ISSUE TITLE
Evaluate range queries

### ISSUE THREAD

**Issue by raminqaf** [bakdata/quick#28]
Currently, quick only supports point queries. Some use-cases need the support of range queries. [Interactive Queries](https://docs.confluent.io/platform/current/streams/developer-guide/interactive-queries.html#kstreams-interactive-queries) enable querying the state store in Kafka Streams. For range queries we found these approaches:

- Use the `range()` method in the `ReadOnlyKeyValueStore` [interface](https://github.com/apache/kafka/blob/3.2/streams/src/main/java/org/apache/kafka/streams/state/ReadOnlyKeyValueStore.java#L60). 
- Another possibility is to use the `prefixScan()` [method](https://github.com/apache/kafka/blob/2.8/streams/src/main/java/org/apache/kafka/streams/state/ReadOnlyKeyValueStore.java#L119).
- The newest release of Kafka 3.2 comes with [Interactive Queries v2](https://www.confluent.io/blog/apache-kafka-3-2-0-new-features-and-updates/#kip-796-kip-805), which adds a `RangeQuery` class to the IQs. 

We should evaluate these approaches and set up a road map for the implementation.

**Comment by DawidNiezgodka** [comment]
We might also take a look at this utility class: https://hbase.apache.org/apidocs/org/apache/hadoop/hbase/util/OrderedBytes.html

**Comment by DawidNiezgodka** [comment]
The following approaches were examined:
1. Flattened Strings,
2. Converting an avro to the byte array,
3. Converting a proto to the byte array,
4. Using a custom comparator.

Because of the specifics of the serialisation in both avro and proto, it is difficult to implement range queries as the order is not kept in a desired way. 
Using a custom comparator is challenging as there is no simple method to exchange it with the default one (for example, through dependency injection). One possible approach would be to implement a custom state store but again this is challenging.
It seems that the most convenient method is the use of flattened strings.

Concerning the approach with flattened strings:
1. For single index or multi-index, it's easy and works good,
2. If we include a range, then it makes no difference whether it's a simple range, range + index, or range + multi-index,
3. In the case of (multi)index + multi-range, it is not possible to make a query in a single run as the nature of lexicographical order prohibits this.

**Comment by raminqaf** [comment]
# Benchmark

## List vs. Range

### Setup
For _N_ values for userId "askm", how fast are writes and reads when:
1. we use one list for all the values
2. we use a range for each value

For the first approach we have one record with list of _N_ values. In the second approach we have _N_ key/value pairs.

#### List

| Key/Value  | 
| ------------- |
| askm -> [a, b ,c ,d ,e]  | 

#### Range

| Key/Value  | 
| ----------- |
| askm_1 -> a  | 
| askm_2 -> b | 
| askm_3 -> c | 
| askm_4 -> d | 
| askm_5 -> e | 

Possible values for _N_: 10/100/1000/10000/100000/1000000

To keep the experiments setup simple we avoid any CF and store the data as Key/Value in RocksDB.

The values should be unique IDs. These values represent pointers to the actual value in the Value CF later on.

### Write latency
For each _N_ values we should ingest the data into RocksDB and calculate the average write time. The list approach should append the data to the list and the range approach should set a new key/value pair in RocksDB.

### Read latency
For the list approach we send only one get request (`get("askm")`) to retrieve the whole list. For the range approach we have to send a range request (`prefix_scan(askm_)`) to retrieve all the values. This can be done using the [Prefix Seek](https://github.com/facebook/rocksdb/wiki/Prefix-Seek)

### Memory consumption (Nice to have)
It would be nice to calculate the memory consumption of each approach.

**Comment by raminqaf** [comment]
We are now planning to implement the range query functionality. For more information, refer to #55
